## Manipulating tensors  ( tensor  operations)


Basic Operations

+ , - , /, *

In [10]:
# you can add a value to a tensor using  the addition   operator
import tensorflow as tf

tensor = tf.constant([[10,7],[3,4]])
tensor + 10     # this will add 10 to every element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

# multiplication


In [5]:
tensor * 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

# Subtraction

In [8]:
tensor - 2 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]])>

# Divide

In [11]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

# we can use tensorflow built in functions

In [13]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

**matrix multiplication**     

In machine  learning, matrix multiplication is  one  of the commen operations.

In [16]:
print(tensor)
tf.matmul(tensor,tensor)       # multiple 2  matrixs: ttf.linaLg.matmul  :-> linalg= linear algebra



tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [18]:
# matrix multiplication  with python  operator  "@"
tensor @ tensor     # for both method their is rule for matrix multiplication { [3,2] * [2,3] -> inner dimension should be same}

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

# Reshape matrix

In [21]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# reshape this [3 X 2] matrix 
tf.reshape(X, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [23]:
X.shape, tensor.shape

(TensorShape([3, 2]), TensorShape([2, 2]))

#  transpose of matrix

In [25]:
# can do same with transpose 
X, tf.transpose(X), tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

# the Dot product

In [29]:
# matrix multiplication is also referred to as the dot product
# make  another tensor Y
Y = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>)

In [32]:
# perform  the dot product x and y

tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]])>