In [3]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

## Squeezing the tensors (  removing all single dimension)

In [4]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[1,1,1,50]))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [5]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One Hot encoding tensors

In [11]:
#  Create  a list  of indices
some_list = [0,1,2,3] # could be red ,green  blue ,purple : here numbers are postions
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [14]:
# specify custom  values  for one hot encoding
tf.one_hot(some_list,depth=4,  on_value="yo i love deep learning",off_value="i also like to code")
#tf.one_hot(some_list,depth=4,  on_value="Y",off_value="S")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like to code',
        b'i also like to code', b'i also like to code'],
       [b'i also like to code', b'yo i love deep learning',
        b'i also like to code', b'i also like to code'],
       [b'i also like to code', b'i also like to code',
        b'yo i love deep learning', b'i also like to code'],
       [b'i also like to code', b'i also like to code',
        b'i also like to code', b'yo i love deep learning']], dtype=object)>

### Squaring,Log,square root

In [16]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [18]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [23]:
# Find squareRoot
# tf.sqrt(H)  # this is give type error sqrt only takes bfloat and half etc paramters :soo typecast it
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [26]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

### Tensorflow interacts  beautifully with numpy arrays

In [28]:
# Create a tensor directly from numpy array
J = tf.constant(np.array([3.,2.,7.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 2., 7.])>

In [31]:
# Convert our tensor  back to a numpy array
np.array(J), type(np.array(J))

(array([3., 2., 7.]), numpy.ndarray)

In [33]:
# convert tensor  J to numpy  array using numpy fun directly
J.numpy(), type(J.numpy())


(array([3., 2., 7.]), numpy.ndarray)

In [34]:
# the default type of each are slightly different
numpy_J = tf.constant(np.array([3.,4.,5.])) 
tensor_J = tf.constant([3.,4.,5.])
# check the dataype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)