In [6]:
# introduction to Tensors
# import Tensorflow
import tensorflow as tf
print(tf.__version__)



2.15.0


In [7]:
# creating first tensor
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
# check the number of dimensions of tesnors(ndim  stands for  number of dimensions)
scaler.ndim

0

In [15]:
#  Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [17]:
# checks the dimensions of vector
vector.ndim

1

In [21]:
# create  a matrix  ( has  more  than 1 dimensions)
matrix  = tf.constant([ [10,7,] ,[8,10] ])
matrix
# output ->   <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10],[8,10])>
matrix.ndim     # output 2D

2

In [30]:
# create another matrix 
another_matrix = tf.constant([[1.3,2.3],
                              [3,4],
                              [1,4]], dtype=tf.float16)   # specify the data type with  dtype parameter
another_matrix
# this will give all float16 values see


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1.3, 2.3],
       [3. , 4. ],
       [1. , 4. ]], dtype=float16)>

In [34]:
# let's create a tensor 
tensor = tf.constant([    # this is 3D            # this is 3D [ [ [1,2,3],[4,5,6] ] ]
    [[1,2,3],
     [4,5,6]
    ]])
tensor.ndim

3

In [38]:
# create the same tensor with tf.varibale() as above
changeable_tensor = tf.Variable([10,7])
Unchangeable_tensor = tf.constant([10,7])
changeable_tensor,Unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [43]:
# let's try to change one of the element in our changeable tensor by using .assign()
changeable_tensor[0].assign(90)  # 10 to 90

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([90,  7])>

In [45]:
# lets try to change one of the element unchangeable tensor 
Unchangeable_tensor[0].assign(100)
Unchangeable_tensor      # this is not allowed because this is constants 

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [53]:
# creating Random tensors 
# Random tensors are tensor of some arbitary  size  which contains random numbers
random_1=  tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2,
# Are they equal? ans-> Yes for same seed no 
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [73]:
# Shuffle the order of the element in a tensor
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
tf.random.shuffle(not_shuffled)              # this will  directly shufflle randomly
tf.random.set_seed(42)                       # this is global level seed
tf.random.shuffle(not_shuffled,seed=42)      # this is operation level seed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [75]:
# create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [81]:
# other ways to make Tensor (e.g) Usinf Numpy

# create a tensor of all zeros
tf.zeros(shape=(3,2))  

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>