In [18]:
import tensorflow as tf
import numpy as np

# Changing the datatype of a tensor

In [5]:
# create a mew tensor with  default  datatype (float 32)
B = tf.constant([1.7,7.4])
C = tf.constant([1,7])
B.dtype,C.dtype


(tf.float32, tf.int32)

In [9]:
# changing from  float32 to float16 ( reduced precision)
B = tf.cast(B,dtype = tf.float16)
B.dtype

tf.float16

In [12]:
# changing from int32 to float32
C = tf.cast(C , dtype = tf.float32)
C.dtype

tf.float32

# Aggregating  tensors
 aggregatting tensors =  consdesing  them  from multiple values down  to a smaller amount  of values

In [14]:
# Get  the  absolute  values
D = tf.constant([-7, -10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [16]:
# Get  the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [30]:
# Create  a random  tensor with values  between  0 and 100  of size 50 
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([77, 41, 48, 50, 27, 97, 52, 96, 68, 48, 10, 40, 33, 31, 50, 39, 86,
       96,  9, 89, 27, 55, 91, 19, 69, 28, 67, 32, 10, 31,  9, 81, 23,  7,
       56, 21, 64, 13, 73, 80, 59, 94, 22, 44, 12, 52, 55, 52, 78, 55])>

In [26]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

This will give the minimum element 

In [31]:
np.min(E)

7

Find the Minimum or maximum, element using tf function

In [37]:
print('minimum',tf.reduce_min(E))
print('Maximum:',tf.reduce_max(E))

minimum tf.Tensor(7, shape=(), dtype=int32)
Maximum: tf.Tensor(97, shape=(), dtype=int32)


### Find the Mean

In [39]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

### Find the Sum

In [44]:
tf.reduce_sum(E)
tf.reduce_prod(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

# Home work find variance  and standard deviation of our E