## Standard deviation

In [3]:
import tensorflow_probability as tfp

In [13]:
import tensorflow as tf
import numpy as np

E = tf.constant(np.random.randint(0, 100, size=50))
E
# find varince using tf
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=810.4576>

### find the variance  of our tensor using tensorflow_probability 

In [7]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=666>

### Find the standard deviation in our tensors using tensorflow_probability  

In [14]:
# finding standard dev using tensorflow 
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.468536>

## Find the positional maximum and minimum

In [16]:
# Create a new tensor and find the positional max and mim
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5942943 , 0.352116  , 0.51593244, 0.80377066, 0.23978364,
       0.8119563 , 0.9410391 , 0.8270842 , 0.83006215, 0.321285  ,
       0.94366944, 0.45865476, 0.8563067 , 0.45645845, 0.19846213,
       0.0453639 , 0.9118004 , 0.6313281 , 0.14974701, 0.45277357,
       0.6881945 , 0.7399801 , 0.6769029 , 0.6606914 , 0.03909457,
       0.48114252, 0.9707564 , 0.89435697, 0.33849347, 0.67513645,
       0.615777  , 0.00537801, 0.21202183, 0.8105148 , 0.7943617 ,
       0.31551087, 0.03697526, 0.7963891 , 0.19247615, 0.2689345 ,
       0.7923472 , 0.4853965 , 0.42581546, 0.57878995, 0.49588668,
       0.38184237, 0.117203  , 0.0895381 , 0.13763297, 0.18672752],
      dtype=float32)>

In [18]:
# find the positional maximum
tf.argmax(F)  ## same as np.armax


<tf.Tensor: shape=(), dtype=int64, numpy=26>

In [20]:
# Index on our largest value position 
F[tf.argmax(F)]   # or check by tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9707564>

In [24]:
# Check the equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [26]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [27]:
# find the minimum  using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.005378008>