In [51]:
# turn numpy array into tensor
# the main difference between Numpy arrays and TensorFlow tensor is that tensor can be run on a GPU ( much faster
# for numaerical computing)
import tensorflow as tf
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create  a  Numpy array  between 1 and  25
numpy_A

# x = tf.constant(some_matrix) # capital  for matrix or tensor
# y= tf.constant(vector)  # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [52]:
A = tf.constant(numpy_A, shape=(3,8))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [53]:
## Getting information from tensors

# Create a rank 4 tensor ( 4D)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
# find the size ,shape ,ndim  for above
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [55]:
# Get various attributes  of our tensor
print("Datatype  of every element :", rank_4_tensor.dtype)
print("Number of dimension (rank) :", rank_4_tensor.ndim)
print("Shape of our tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis :", rank_4_tensor.shape[0])
print("Elements along  the last axis :", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
# use her numpy at the last if you dont want the tf type and all 
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())


Datatype  of every element : <dtype: 'float32'>
Number of dimension (rank) : 4
Shape of our tensor: (2, 3, 4, 5)
Elements along the 0 axis : 2
Elements along  the last axis : 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


# Indexing  tensors
## tensors can be  indexed just  like  python list

In [56]:

some_list = [1,2,3,4]
some_list[:2]           # this will print  first 2 elements of list


[1, 2]

In [57]:
# Get the first 2 elements  of each  dimesion
rank_4_tensor[:2,:2,:2,:2]       


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [58]:
# Get the first element from each dimensions  from each index  except  from the final one  
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [59]:
# Create a rank 2 tensor ( 2 Dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim, tf.size(rank_2_tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [60]:
# Get the last item of each of row  of our  rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [61]:
# add  in extra  dimension to our rank 2 tensor
rank_3_tensor= rank_2_tensor[..., tf.newaxis]   # here 3 dot notation ( ellipsis notaiton) is using for slicing multi dimension array/tensor
rank_3_tensor.ndim 

3

In [64]:
# Alternative to  tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1)    # "-1" means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [66]:
tf.expand_dims(rank_2_tensor, axis = 0)     # "0" means expand the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>